version: '3'

services:

  web:

    build: .
    container_name: drf_app
    volumes:
      - ./src:/drf

    ports:
      - "9090:8000"

    depends_on:
      - database

    links:
      - redis

  database:

    image: 'postgres:latest'
    container_name: pgdb
    ports:
      - "5432:5432"
    expose:
      - '5432'

    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: maz # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)

  redis:
      image: 'redis:latest'
      ports:
        - "6379:6379"