version: '3'

services:

  web:

    build: .
    container_name: project_app
    volumes:
      - ./src:/drf

    ports:
      - "8080:8000"

    depends_on:
      - db

    links:
      - redis


  db:

    image: 'postgres:latest'
    ports:
      - "5432:5432"
    container_name: postgres

    environment:
      POSTGRES_USER: mujtaba # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: maz # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: postgres

  redis:
      image: 'redis:latest'
      ports:
        - "6379:6379"
