# Generated by Django 4.1.4 on 2023-01-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unread_messages', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('box_detail', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
