# Generated by Django 4.1.4 on 2022-12-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box', '0001_initial'),
        ('room', '0001_initial'),
        ('chatter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='chatter',
            field=models.ManyToManyField(blank=True, to='chatter.chatter'),
        ),
        migrations.AddField(
            model_name='box',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_owner', to='chatter.chatter'),
        ),
        migrations.AddField(
            model_name='box',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_room', to='room.room'),
        ),
    ]
